# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b97745a4b22bfbe315ecb38f82d5e31e86f43e75a8737d9622025602ea6484995dd3b5e564b0dbac3c6895ffb422f23880215257bb334c420821522ea957383

test:
  secret_key_base: 1a6869fc836b37bfc0806004f0a6539c5fd9a8594f79dd42da9a63349e295c4f0ce4fb06c893508eed5642d7585b95d82c836e22f713414c6f1e37772f1a6c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
